version: '3.8'

services:

  frontend:
    ports:
    - ${REACT_PORT}:8080

  pgAdmin:
    image: dpage/pgadmin4:4
    restart: always
    depends_on:
    - postgres
    ports:
    - ${PGADMIN_PORT}:80
    volumes:
    - type: volume
      source: pgAdmin_data
      target: /var/lib/pgadmin/
    networks:
    - back_tier
    environment:
    - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
    - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}


volumes:
  pgAdmin_data: